- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: true
    force_apt_get: yes

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - python3-pip
      - virtualenv
      - python3-setuptools
      - git
    state: latest
    update_cache: true
